addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database bandcamp_api_test;' -U postgres
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.0
script:
  - HANAMI_ENV=test bundle exec hanami db prepare
  - bundle exec rspec
